name: Deploy CDK Stack

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.event.inputs.image_tag || github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "npm"
          cache-dependency-path: "deploy/cdk/package-lock.json"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION || 'us-east-1' }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install CDK dependencies
        run: |
          cd deploy/cdk
          npm ci

      - name: Deploy CDK stack with container
        run: |
          cd deploy/cdk
          npx cdk deploy --require-approval never \
            --context environment=${{ github.environment }} \
            --context githubOrg=${{ vars.GITHUB_ORG || 'FMGSuite' }} \
            --context githubApiVersion=${{ vars.GITHUB_API_VERSION || '2022-11-28' }} \
            --context githubApiScope=${{ vars.GITHUB_API_SCOPE || 'organization' }} \
            --context imageTag=${{ env.IMAGE_TAG }} \
            --context dockerDirectory=../../src/background
        env:
          CDK_DEFAULT_REGION: ${{ vars.AWS_REGION || 'us-east-1' }}
